"""Create Subscription table

Revision ID: 1459768496e3
Revises: 687d307ef486
Create Date: 2024-10-03 00:37:52.488174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1459768496e3'
down_revision = '687d307ef486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=10000),
               existing_nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=10000),
               existing_nullable=False)
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=10000),
               existing_nullable=False)
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=10000),
               existing_nullable=False)
        batch_op.alter_column('img_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=10000),
               existing_nullable=False)
        batch_op.alter_column('subtitle',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=10000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.alter_column('subtitle',
               existing_type=sa.String(length=10000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.alter_column('img_url',
               existing_type=sa.String(length=10000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.alter_column('author',
               existing_type=sa.String(length=10000),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)
        batch_op.alter_column('body',
               existing_type=sa.String(length=10000),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.String(length=10000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=10000),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###
